name: Build everything on release

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Assemble distribution
        run: >
          ./gradlew
          assembleFullDist

      - name: Attach artifacts to the release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'build/full-distribution/cookiemover-full.zip'
          file_glob: true
          tag: ${{ github.ref }}